source "https://rubygems.org"

gem 'fluentd'
gem 'fluent-plugin-record-reformer'
gem 'fluent-plugin-s3'
gem 'fluent-plugin-kinesis'
gem 'fluent-plugin-kafka'
gem 'fluent-plugin-elasticsearch', '>= 5.3.0'
gem 'fluent-plugin-mongo', '>= 1.6.1'
gem 'fluent-plugin-webhdfs'
gem 'fluent-plugin-rewrite-tag-filter'
gem 'fluent-plugin-cloudwatch-logs'
gem 'fluent-plugin-concat'
