source "https://rubygems.org"

gem "rails", "~> 7.0.8", ">= 7.0.8.7"
gem "propshaft", ">= 1.3.2"
gem "puma"
gem "pg"
gem "activerecord-nulldb-adapter", require: false

# See also https://github.com/ankane/pghero/blob/v3.3.4/guides/Rails.md
gem "pghero"
gem "pg_query"
gem "aws-sdk-cloudwatch"
gem "google-apis-monitoring_v3", ">= 0.72.0"
gem "azure_mgmt_monitor"
